server:
  port: 8083

spring:
  application:
    name: cart
  data:
    redis:
      host: localhost
      port: 6379

otel:
  traces:
    exporter: otlp
  metrics:
    exporter: none
  logs:
    exporter: none
  exporter:
    otlp:
      endpoint: http://localhost:4317
      protocol: grpc
  springboot:
    enabled: true
  instrumentation:
    spring-webmvc:
      enabled: true
    spring-webflux:
      enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [trace=%X{traceId:-},span=%X{spanId:-}] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.tempo.cart: DEBUG
    org.springframework.web: INFO